# Generated by Django 5.1.6 on 2025-02-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
